FROM postgis/postgis:16-3.4

RUN sed -i '/debian-security/d' /etc/apt/sources.list \
    && apt-get update \
    && apt-get install -y --no-install-recommends postgresql-16-pgvector \
    && rm -rf /var/lib/apt/lists/*
