services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      POSTGRES_DB: asg_sp
      POSTGRES_USER: asg_user
      POSTGRES_PASSWORD: asg_pass
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./asg_sistema/db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql

volumes:
  pgdata:
